version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: events_db
      POSTGRES_USER: events_user
      POSTGRES_PASSWORD: events_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cmd/server/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:

